### PR TITLE
Added static directory to hold css files and js files

### PR DESCRIPTION
**Pull request by MichaelClarkFsu**
Moved css files and js files into static directory.

### CODE REVIEW

**Comment by KPCOFGS** [comment]
I see app.py file gets changed, any reason for the change?

**Comment by MichaelClarkFsu** [comment]
After looking at it I don't think so. I think in order for flask to recognize the css and js files we have to put them in the static directory. I believe the code you added can stay the same.

**Comment by MichaelClarkFsu** [comment]
Yes. After putting them both in the static folder the application ran just as before with your added dark mode toggle button. I believe its a flask specific problem where we have to specify a static folder.

**Comment by MichaelClarkFsu** [comment]
I'm unsure about the database changes made. It notified me of a merge conflict when I pulled the changes onto my machine. Maybe because there was a database already there?

**Comment by KPCOFGS** [comment]
I see the problem now. We have `image`, `css`, and `scripts` folder. I looked up how to format the `static` folder and you can create a `static` folder with the following format:

Common Contents of a static Folder:

    Images: Icons, logos, or other visual assets like .jpg, .png, .svg, etc.
        Example: static/images/logo.png

    CSS Files: Stylesheets that define the appearance of the site.
        Example: static/css/styles.css

    JavaScript Files: Client-side JavaScript code for interaction and functionality.
        Example: static/js/main.js

    Fonts: Web fonts or other font assets used on the website.
        Example: static/fonts/roboto.woff

    Videos: Video files like .mp4, .webm, etc., used in the application.
        Example: static/videos/tutorial.mp4

    Other Assets: Any other files that need to be directly served, like PDFs, XML files, or data files.
        Example: static/docs/user-manual.pdf

**Comment by KPCOFGS** [comment]
You can create the `static` folder in that format, move `css` folder inside of it, rename `scripts` folder to `js` and move it inside `static` folder, and move `images` folder inside `static` folder as well. After you do that, create a pull request, so Dr. Mills knows your contribution

**Pull request closed without merging**
